import { createStitches } from "@stitches/react";

export const {
  styled,
  css,
  globalCss,
  keyframes,
  getCssText,
  theme,
  createTheme,
  config,
} = createStitches({
  theme: {
    colors: {
      text: "#eeeeee",
      background: "black",
      base: "black",
      "1": "#121212",
      "2": "#1a1a1a",
      "3": "#262626",
      "4": "#333333",
      "5": "#404040",
      "6": "#4d4d4d",
      drag1: "#cfe8ff",
      drag2: "#b7d1b5",
      "drag1-background": "rgba(128, 128, 128, 0.15)",
      "drag2-background": "rgba(128, 128, 128, 0.15)",
      overflow: "gray",
      "tabset-background": "$1",
      "tabset-background-selected": "$1",
      "tabset-background-maximized": "$6",
      "tabset-divider-line": "$4",
      "tabset-header-background": "$1",
      "tabset-header": "$text",
      "border-background": "$1",
      "border-divider-line": "$4",
      "tab-selected": "$text",
      "tab-selected-background": "$4",
      "tab-unselected": "gray",
      "tab-unselected-background": "transparent",
      "tab-textbox": "$text",
      "tab-textbox-background": "$3",
      "border-tab-selected": "$text",
      "border-tab-selected-background": "$4",
      "border-tab-unselected": "gray",
      "border-tab-unselected-background": "$2",
      splitter: "$2",
      "splitter-hover": "$4",
      "splitter-drag": "$5",
      "drag-rect-border": "$4",
      "drag-rect-background": "$1",
      "drag-rect": "$text",
      "popup-border": "$6",
      "popup-unselected": "$text",
      "popup-unselected-background": "black",
      "popup-selected": "$text",
      "popup-selected-background": "$4",
      "edge-marker": "gray",
    },
  },
});
